# Generated by Django 4.2.16 on 2025-02-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_cart_is_auctioned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_auctioned',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_auction_product',
        ),
    ]
